/** Isolated development fixtures; excluded from the public barrel. */
import React, { useState } from 'react';
import * as K from './index';
export const scenes = ['overview', 'auction', 'rent', 'jail', 'card', 'purchase', 'player', 'trade', 'log', 'teams', 'workers', 'winner', 'waiting'];
const names = ['You', 'Alexandria Montgomery', 'Priya', 'Noah', 'Maya', 'Leo', 'Charlie', 'Sofia'];
const cities = ['London', 'Paris', 'Tokyo', 'New York', 'Sydney', 'Dubai', 'Singapore', 'Hong Kong'];
const colors = ['#06b6d4', '#f43f5e', '#f59e0b', '#10b981', '#8b5cf6', '#3b82f6', '#ec4899', '#f97316'];
const players = names.map((name, i) => ({ name, color: colors[i], marker: i + 1, icon: ['🌊','🌹','🔶','💚','⚡','🌙','🌸','🔥'][i], isYou: i === 0, isBot: i === 6, isAway: i === 5, isBankrupt: i === 7 }));
export function KitPreview({ scene = 'overview' }: { scene?: string }) {
  const [message, setMessage] = useState('No action yet');
  const [open, setOpen] = useState(true);
  const [copied, setCopied] = useState(false);
  const [method, setMethod] = useState<'pay'|'card'>('pay');
  const [draft, setDraft] = useState<K.TradeDraft>({ toPlayer: names[1], offeredProperties: ['p0'], requestedProperties: ['p1'], offeredCash: '125000', requestedCash: '0' });
  const act = (label: string) => () => setMessage(label);
  const close = () => { setOpen(false); setMessage('Closed'); };
  const rent = { propertyName: 'London', owner: names[1], amount: 2250000, balance: 1000000, onPay: act('Bankruptcy requested'), onManageAssets: act('Manage assets requested') };
  const jail: K.JailDialogBodyProps = { turnsRemaining: 2, fine: 50000, balance: 10234567, jailCards: 1, method, onMethodChange: setMethod, onPay: act('Bail requested'), onStay: act('Stay requested'), onUseCard: act('Jail card requested') };
  const card: K.CardDialogBodyProps = { type: 'chance', amount: 125000, isReward: false, diceRoll: 8, income: 250000, numProperties: 4, jailCard: true, onResolve: act('Card resolved'), onDetails: act('Calculation requested') };
  const purchase = { propertyName: 'Singapore', price: 2200000, balance: 10234567, onBuy: act('Purchase requested'), onDecline: act('Auction requested'), declineLabel: 'Start auction' };
  let content: React.ReactNode;
  if (['rent','jail','card','purchase','auction'].includes(scene)) {
    const bodies: Record<string, React.ReactNode> = { rent: <K.RentDialogBody {...rent} actionsInBody={false} />, jail: <K.JailDialogBody {...jail} actionsInBody={false} />, card: <K.CardDialogBody {...card} actionsInBody={false} />, purchase: <K.PurchaseDialogBody {...purchase} actionsInBody={false} />, auction: <K.AuctionStatus propertyName="Tokyo" currentBid={1250000} highestBidder={names[1]} you="You" secondsLeft={12} totalSeconds={120} minIncrement={100000} quickBids={[1350000,1500000,20000000]} balance={10234567} isSeller={false} hasBid isDraft draftIndex={3} draftTotal={28} onBid={n => setMessage(`Bid ${n}`)} /> };
    const footers: Record<string, React.ReactNode> = { rent: <K.RentDialogActions {...rent} />, jail: <K.JailDialogActions {...jail} />, card: <K.CardDialogActions {...card} />, purchase: <K.PurchaseDialogActions {...purchase} /> };
    content = open && <K.ActionStage kind={scene as K.ActionStageProps['kind']} title={{rent:'Rent due',jail:'In jail',card:'Chance card',purchase:'Buy property',auction:'Auction'}[scene]} subtitle="Your decision" footer={footers[scene]} onDismiss={close}>{bodies[scene]}</K.ActionStage>;
  } else if (scene === 'player') content = <K.PlayerSheet open={open} onClose={close} player={players[0]} balance={10234567} netWorth={18234567} rank={1} properties={cities.map((name,i) => ({id:`p${i}`,name,group:'Global property',value:2000000+i*250000,rent:125000,isMortgaged:i===1,isInactive:i===7,actionLabel:i===1?'Unmortgage · $1.1M':'Mortgage property',disabledReason:i===2?'Sell buildings across this group first.':undefined}))} onPropertyAction={id=>setMessage(id)} onReorder={ids=>setMessage(ids.join(', '))} />;
  else if (scene === 'trade') content = <K.TradeSheet open={open} onClose={close} you="You" recipients={names.slice(1,7)} draft={draft} onDraftChange={setDraft} offeredChoices={[{id:'p0',name:'London'},{id:'p2',name:'Tokyo',lockedReason:'Buildings in this group prevent trading.'}]} requestedChoices={[{id:'p1',name:'Paris'}]} offers={[{id:'offer1',fromPlayer:names[1],toPlayer:'You',offeredNames:['Paris'],requestedNames:['London'],offeredCash:125000,requestedCash:0,expiresAt:600000,canAccept:true,canReject:true}]} now={300000} onSubmit={act('Offer submitted')} onAccept={act('Offer accepted')} onReject={act('Offer rejected')} />;
  else if (scene === 'log') content = <K.LogSheet open={open} onClose={close} entries={cities.map((city,i)=>({id:`e${i}`,player:names[i],message:`${i%2?'Paid rent at':'Purchased'} ${city}`,amount:i%2?-125000:200000,timeLabel:`${i+1} min ago`,type:i%2?'Rent':'Purchase'}))} />;
  else if (scene === 'teams') content = <K.TeamsSheet open={open} onClose={close} yourTeamId="t1" teams={[{id:'t1',name:'Cyan Alliance',members:players.slice(0,4),combinedCash:32123456},{id:'t2',name:'Rose Alliance',members:players.slice(4),combinedCash:21023456,canJoin:true,disabledReason:'You already belong to a team.'}]} onJoin={act('Join requested')} onCreate={act('Create requested')} />;
  else if (scene === 'workers') content = <K.WorkersSheet open={open} onClose={close} assignments={cities.map((propertyName,i)=>({propertyId:`p${i}`,propertyName,color:colors[i],assigned:i%2===0,disabledReason:i===1?'Mortgage must be cleared first.':undefined}))} onAssign={id=>setMessage(`Assign ${id}`)} onRemove={id=>setMessage(`Remove ${id}`)} onColorChange={(id,color)=>setMessage(`${id}: ${color}`)} />;
  else if (scene === 'winner') content = <K.GameOverCard winnerName="You" standings={players.map((player,i)=>({player,rank:i+1,netWorth:18234567-i*2200000}))} onBackToLobby={act('Back to lobby')} />;
  else if (scene === 'waiting') content = <K.WaitingRoom roomCode="654321" seats={players} maxPlayers={8} isHost onStart={act('Start requested')} onCopy={()=>setCopied(true)} copied={copied} onEditProperties={act('Editor requested')} />;
  else content = <><K.TurnStatus actorName="You" isMine secondsLeft={17} totalSeconds={90} phase="Roll or manage properties" /><h2>Global board · turn 14</h2><div className="fixture-grid">{cities.map((name,i)=><K.PropertyTile key={name} name={name} price={2000000+i*250000} ownerName={names[i]} ownerColor={colors[i]} colorGroup={colors[i]} houses={i===0?2:0} hasHotel={i===2} isMortgaged={i===1} isInactive={i===7} isInAuction={i===3} tokens={[{name:names[i],icon:players[i].icon,marker:i+1}]} teamName={i<4?'Cyan Alliance':undefined} selected={i===0} size="map" onSelect={()=>setMessage(name)} />)}</div><K.SelectedTileSummary name="London" price={2000000} rent={125000} ownerName="You" onDetails={act('Details requested')} /><K.PropertyTile name="London" price={2000000} ownerName="You" ownerColor={colors[0]} houses={2} size="full" /><div className="mma-list">{players.map(p=><K.PlayerIdentity key={p.name} {...p} />)}</div><h3>Signed, exact accessible currency</h3><p><K.CurrencyAmount amount={10234567} /> / <K.CurrencyAmount amount={-2250000} signed /> / <K.CurrencyAmount amount={125000} signed /></p><K.KitButton variant="primary" onClick={act('Roll requested')}><K.Icon name="dice" />Roll dice</K.KitButton></>;
  return <main className="mma-ui fixture"><button className="fixture-launch" onClick={()=>setOpen(true)}>Open {scene}</button><p role="status" data-preview-status>{message}</p>{content}</main>;
}
