import React from 'react';
const dots: Record<number, number[]> = { 1: [4], 2: [0, 8], 3: [0, 4, 8], 4: [0, 2, 6, 8], 5: [0, 2, 4, 6, 8], 6: [0, 2, 3, 5, 6, 8] };
export interface DiceProps {
    /** Actual engine result, never randomly generated by presentation. */ values: readonly [
        number,
        number
    ];
    /** Caller controls rolling phase. */ rolling?: boolean;
    /** Caller supplies doubles state. */ doubles?: boolean;
    /** Optional authorized roll action. */ onRoll?: () => void;
    /** Reason the roll cannot currently run. */ disabledReason?: string;
}
export function Dice({ values, rolling, doubles, onRoll, disabledReason }: DiceProps) {
    return <div className={`mp-dice ${rolling ? 'mp-rolling' : 'mp-settled'} ${doubles ? 'mp-doubles' : ''}`}><div className="mp-dice-pair" role="img" aria-label={rolling ? 'Dice rolling' : `Dice ${values[0]} and ${values[1]}${doubles ? ', doubles' : ''}`}>{values.map((value, i) => <div key={i} className="mp-die" aria-hidden="true">{Array.from({ length: 9 }, (_, j) => <i key={j} className={(dots[value] || dots[1]).includes(j) ? 'mp-pip' : ''}/>)}</div>)}</div>{onRoll && <button className="mp-button mp-primary" type="button" onClick={onRoll} disabled={rolling || !!disabledReason}>Roll Dice</button>}{disabledReason && <p className="mp-muted">{disabledReason}</p>}</div>;
}
