import React, { useState } from 'react';
import * as P from './index';
import { CityArt } from '../cards/CityArt';
import MonopolyBoardLayout from '../../components/game/MonopolyBoardLayout';
import type { Player, Property } from '../../types/game';
export const scenes = ['board', 'tiles', 'players', 'navigation', 'stages', 'auction', 'feedback', 'game-over', 'empty', 'waiting', 'before-board'] as const;
export const players: P.Identity[] = ['You', 'Priya', 'Alexandra', 'Noah', 'Maya', 'Leo', 'Amara', 'Kai'].map((name, i) => ({ id: `p${i}`, name, color: ['#79ddff', '#ffb2c0', '#ffe49a', '#8cf0c5', '#c2b4ff', '#ffb4d8', '#b0d6ff', '#ffc49a'][i], token: ['🌊', '🌹', '🔶', '💚', '⚡', '🌙', '🌸', '🔥'][i] }));
const names = ['GO', 'London', 'Community Chest', 'Paris', 'Income Tax', 'Trans-Siberian Railway', 'New York', 'Chance', 'Los Angeles', 'Toronto', 'Jail', 'Tokyo', 'Electric Company', 'Seoul', 'Shanghai', 'Orient Express', 'Sydney', 'Community Chest', 'Melbourne', 'Auckland', 'Free Parking', 'Rome', 'Chance', 'Madrid', 'Berlin', 'Indian Pacific', 'Dubai', 'Mumbai', 'Water Works', 'Delhi', 'Go To Jail', 'Hong Kong', 'Bangkok', 'Community Chest', 'Cape Town', 'Eurostar', 'Chance', 'Singapore', 'Luxury Tax', 'Monaco'];
const code = ['GO', 'LON', 'CC', 'PAR', 'TAX', 'TSR', 'NYC', '?', 'LAX', 'TOR', 'JAIL', 'TYO', 'PWR', 'SEL', 'SHA', 'ORX', 'SYD', 'CC', 'MEL', 'AKL', 'PARK', 'ROM', '?', 'MAD', 'BER', 'IPC', 'DXB', 'BOM', 'H2O', 'DEL', 'G2J', 'HKG', 'BKK', 'CC', 'CPT', 'EUR', '?', 'SGP', 'TAX', 'MCO'];
const kindFor = (i: number): P.BoardTileProps['kind'] => i === 0 ? 'go' : i === 10 ? 'jail' : i === 20 ? 'parking' : i === 30 ? 'go-jail' : [2, 17, 33].includes(i) ? 'chest' : [7, 22, 36].includes(i) ? 'chance' : [4, 38].includes(i) ? 'tax' : [5, 15, 25, 35].includes(i) ? 'railroad' : [12, 28].includes(i) ? 'utility' : 'city';
function position(i: number) { return i <= 10 ? { gridRow: 11, gridColumn: 11 - i } : i <= 20 ? { gridRow: 21 - i, gridColumn: 1 } : i <= 30 ? { gridRow: 1, gridColumn: i - 19 } : { gridRow: i - 29, gridColumn: 11 }; }
function orientation(i: number): P.BoardTileProps['orientation'] { return i <= 10 ? 'bottom' : i <= 20 ? 'left' : i <= 30 ? 'top' : 'right'; }
const noop = () => { };
function SingaporeCard() { return <div className="mp-fixture-card"><p className="mp-eyebrow">Dark blue · title deed</p><h2>Singapore</h2><CityArt variant="darkBlue" city="Singapore"/><P.StageStat label="Market value" value="$350,000"/><p className="mp-muted">Illustrative fixture values; integration uses cardAdapters.ts.</p></div>; }
/** Current live board rendered with explicit safe fixtures, no Firebase or game hook. */
function BeforeBoard() { const properties = names.map((name, i) => ({ id: `prop-${i}`, name, position: i, type: kindFor(i) === 'city' ? 'property' : kindFor(i) === 'railroad' ? 'railroad' : kindFor(i) === 'utility' ? 'utility' : 'special', colorGroup: 'darkBlue', color: '#93c5fd', baseValue: 350000, currentValue: 350000, rent: [35000, 175000, 500000, 1100000, 1300000, 1500000], houseCost: 200000, hotelCost: 1000000, mortgageValue: 175000, isMortgaged: false, isInAuction: false, houses: i === 37 ? 2 : 0, hasHotel: false, isOwned: i % 3 === 0, owner: i % 3 === 0 ? players[i % 8].name : undefined })) as Property[]; const seats = players.map((p, i) => ({ id: p.id, name: p.name, color: p.color, pieceIcon: p.token, balance: 1500000, position: [0, 3, 10, 16, 21, 25, 31, 37][i], properties: [], isActive: true, discoveredProperties: Array.from({ length: 40 }, (_, j) => j) })) as Player[]; return <MonopolyBoardLayout properties={properties} players={seats} currentPlayer="p0" playerColor={players[0].color} onPropertyClick={noop} onRollDice={noop} canRoll isMyTurn lastDiceRoll={{ dice1: 3, dice2: 3, total: 6, isDouble: true } as never}/>; }
export function PolishPreview({ scene = 'board' }: {
    scene?: string;
}) {
    const [selected, setSelected] = useState(37), [active, setActive] = useState('properties'), [open, setOpen] = useState(false), [kind, setKind] = useState<P.StageFrameProps['kind']>('rent'), [amount, setAmount] = useState(120000), [notice, setNotice] = useState('Ready'), [rolling, setRolling] = useState(false);
    const nav: P.NavItem[] = (['properties', 'players', 'log', 'trade', 'teams', 'workers'] as const).map((id, i) => ({ id, label: ['Properties', 'Players', 'Log', 'Trade', 'Teams', 'Workers'][i], icon: (['house', 'players', 'log', 'trade', 'teams', 'workers'] as const)[i], active: active === id, badge: id === 'trade' ? 2 : undefined, onClick: () => { setActive(id); setNotice(`${id} selected`); } }));
    const actions: P.Action[] = [{ id: 'confirm', label: 'Confirm action', primary: true, onClick: () => { setNotice('Action requested'); setOpen(false); } }, { id: 'cancel', label: 'Back', onClick: () => setOpen(false) }];
    const board = <P.BoardFrame><div className="mp-fixture-board">{names.map((name, i) => <div key={i} style={position(i)}><P.BoardTile name={name} code={code[i]} kind={kindFor(i)} size="map" orientation={orientation(i)} owner={i % 3 === 0 ? players[i % 8] : undefined} groupColor={players[Math.floor(i / 5) % 8].color} mortgaged={i === 8} neutral={i === 15} auction={i === 37} monopoly={i === 1 || i === 3} teamColor={i === 26 ? '#6555ac' : undefined} hidden={i === 29} houses={i === 37 ? 2 : 0} price={kindFor(i) === 'city' ? '$350K' : undefined} selected={selected === i} onSelect={() => setSelected(i)}/></div>)}<div className="mp-fixture-centre"><p className="mp-eyebrow">Global edition</p><h2>Own the night</h2><P.Dice values={[3, 3]} doubles rolling={rolling} onRoll={() => { setRolling(!rolling); setNotice('Roll requested'); }}/><P.TokenStack players={players} activeId="p0"/></div></div></P.BoardFrame>;
    let content: React.ReactNode;
    if (scene === 'board' || scene === 'before-board')
        content = <><P.TurnBanner player={players[0]} isMine phase="Roll to begin your turn" seconds={17} totalSeconds={30}/><div className="mp-fixture-game"><div className="mp-fixture-board-column">{scene === 'before-board' ? <BeforeBoard /> : board}<div className="mp-summary"><div className="mp-grow"><strong>{selected === 29 ? "Undiscovered tile" : names[selected]}</strong><p className="mp-muted">{selected === 29 ? 'Undiscovered tile' : 'Selected tile · full name and details'}</p></div><button className="mp-button" onClick={() => { setKind('own-property'); setOpen(true); }}>Details</button></div></div><aside className="mp-fixture-dock"><P.DockTabs items={nav}/><P.PlayerCard player={players[0]} cash={amount} netWorth={4200000} rank={2} history={[1, 3, 2, 5, 4, 7, 8]} statuses={['Cyan alliance']}/>{players.slice(1).map((p, i) => <P.PlayerRow key={p.id} player={p} title={p.name} detail={i === 2 ? 'In jail' : 'Ready to play'} trailing={`#${i + 2}`}/>)}</aside></div><div className="mp-fixture-phone-nav"><P.NavBar items={nav}/></div></>;
    else if (scene === 'tiles')
        content = <><h1>Every tile, every state</h1><div className="mp-fixture-tiles">{names.map((name, i) => <P.BoardTile key={i} name={name} code={code[i]} kind={kindFor(i)} price="$350K" owner={players[i % 8]} orientation={orientation(i)} mortgaged={i === 8} neutral={i === 15} auction={i === 37} monopoly={i === 1} hidden={i === 29} teamColor={i === 26 ? '#6555ac' : undefined} houses={i === 37 ? 4 : 0} hotel={i === 39} onSelect={() => setNotice(`${name} selected`)}/>)}</div><P.TokenStack players={players} activeId="p0" movingIds={players.map(p => p.id)}/><P.TokenStack players={players} compact activeId="p0"/><P.Token player={players[1]} moving active/></>;
    else if (scene === 'players')
        content = <><h1>Your empire</h1><P.PlayerCard player={players[0]} cash={amount} netWorth={987654321} rank={2} history={[100, 150, 120, 250, 210, 370, 420]} statuses={['Jail', 'Away', 'Bot', 'Cyan alliance']}/><button className="mp-button" onClick={() => setAmount(amount === 120000 ? 123456789 : 120000)}>Change balance</button><P.PlayerCard player={players[1]} cash={250000} netWorth={1700000} rank={1}/>{players.map((p, i) => <P.PlayerRow key={p.id} player={p} title={p.name} detail={i % 2 ? 'Away · team Aurora' : 'Active · 4 properties'} trailing={P.money(1300000 - i * 100000)}/>)}</>;
    else if (scene === 'navigation')
        content = <><h1>Navigation</h1><P.NavBar items={nav}/><P.DockTabs items={nav}/><P.TurnBanner player={players[2]} phase="Choose your jail action" seconds={7} totalSeconds={30}/><P.TurnBanner player={players[0]} isMine phase="Waiting for the next roll"/><P.Dice values={[2, 5]} rolling={rolling} onRoll={() => setRolling(!rolling)}/><P.Dice values={[6, 6]} doubles disabledReason="Wait for your turn." onRoll={noop}/></>;
    else if (scene === 'stages')
        content = <><h1>One decision owner</h1><div className="mp-dock-tabs">{(['rent', 'card', 'purchase', 'jail', 'auction', 'own-property'] as const).map(k => <button key={k} className="mp-button" onClick={() => { setKind(k); setOpen(true); }}>Open {k}</button>)}</div><P.StageFrame kind="purchase" title="Build your global empire" inline subtitle="An inline frame inside the existing stage" footer={<P.StageActions actions={[{ id: 'buy', label: 'Buy for $350,000', primary: true, onClick: () => setNotice('Buy requested') }, { id: 'locked', label: 'Build house', onClick: noop, disabledReason: 'Own the full colour group first.' }]}/>}><P.StageHero icon="city" title="Singapore"><p>A skyline worth owning.</p></P.StageHero><SingaporeCard /><P.StageStat label="Rent now" value="$35,000" detail="Caller-supplied fixture amount"/></P.StageFrame></>;
    else if (scene === 'auction')
        content = <><h1>Live auction</h1><P.AuctionHall card={<SingaporeCard />} currentBid={amount} leader="Priya" seconds={7} totalSeconds={30} bidders={players} outbid bids={[{ id: 'bid1', label: `Bid ${P.money(amount + 10000)}`, primary: true, onClick: () => { setAmount(amount + 10000); setNotice('Bid requested'); } }, { id: 'bid2', label: 'Bid $500,000', onClick: noop, disabledReason: 'Not enough cash.' }]}/></>;
    else if (scene === 'feedback')
        content = <><h1>Every move has weight</h1><P.Toast title="Rent received" detail="Priya paid $120,000 for Singapore." tone="gain" icon="city" onDismiss={() => setNotice('Toast dismissed')}/><P.Toast title="Mortgage recorded" detail="Your balance has been updated." icon="house"/><P.Toast title="Bid unavailable" detail="Another bidder has already raised the price." tone="loss" icon="trade"/><P.MoneyDelta amount={120000}/><P.MoneyDelta amount={-80000}/><P.AchievementPop title="Global investor" detail="Own a property in every colour group."/><P.LogRow title="Priya paid rent" detail="Singapore · just now" trailing="+$120,000"/><P.TradeRow player={players[1]} title="An offer from Priya" detail="Paris for London + $80,000" icon="trade" trailing="Pending" onSelect={() => setNotice('Trade opened')}/></>;
    else if (scene === 'game-over')
        content = <P.GameOverStage winner={players[0]} winnerLabel="Cyan alliance" standings={players.map((player, i) => ({ player, rank: i + 1, netWorth: 9876543 - i * 750000 }))} actions={[{ id: 'rematch', label: 'Rematch', primary: true, onClick: () => setNotice('Rematch requested') }, { id: 'lobby', label: 'Back to lobby', onClick: () => setNotice('Lobby requested') }]}/>;
    else if (scene === 'waiting')
        content = <><P.StageHero icon="teams" title="The table is almost ready"><p>Room 654321 · Global Edition</p></P.StageHero>{players.map((p, i) => <P.PlayerRow key={p.id} player={p} title={p.name} detail={i === 0 ? 'Host · ready' : 'Connected · ready'} trailing={i === 0 ? 'Host' : 'Ready'}/>)}<P.StageActions actions={[{ id: 'start', label: 'Start game', primary: true, onClick: () => setNotice('Start requested') }]}/></>;
    else
        content = <><h1>Quiet states</h1><P.EmptyState title="Your empire starts here" detail="Buy your first property when you land on an unowned city." action={{ id: 'board', label: 'View board', onClick: () => setNotice('Board requested') }}/><P.EmptyState icon="trade" title="No offers yet" detail="Incoming offers will appear here."/><P.Skeleton rows={4} label="Loading property portfolio"/></>;
    return <main className={`mp-kit mp-fixture ${scene === 'board' || scene === 'before-board' ? 'mp-fixture-one-screen' : ''}`} data-scene={scene}><div className="mp-fixture-body">{content}</div><output className="mp-fixture-status" aria-live="polite">{notice}</output>{open && <P.StageFrame kind={kind} title={kind === 'own-property' ? (selected === 29 ? 'Undiscovered tile' : names[selected]) : `${kind} decision`} subtitle="Only this player's decision is visible" onDismiss={() => setOpen(false)} footer={<P.StageActions actions={actions}/>}><P.StageHero icon={kind === 'jail' ? 'jail' : kind === 'rent' ? 'tax' : 'city'} title="Choose your next move"/><P.StageStat label="Amount" value="$120,000"/>{Array.from({ length: 12 }, (_, i) => <P.ListRow key={i} title={`Property detail ${i + 1}`} detail="Long fixture content to verify the body scrolls while actions stay reachable."/>)}</P.StageFrame>}</main>;
}
