/** Development-only fixtures; not exported from the public barrel. */
import React,{useState} from 'react';
import * as C from './index';
import {KitButton} from '../primitives';
import type {Property} from '../../types/game';
export const scenes=['portfolio','grid','inspect-london','inspect-tokyo','inspect-singapore','chance-back','chance-front','community','special','doubles','trade','auction','performance'];
const rows:[string,Property['type'],string|undefined][]=[['London','property','brown'],['Paris','property','brown'],['Tokyo','property','pink'],['Seoul','property','pink'],['Dubai','property','orange'],['Singapore','property','darkBlue'],['São Paulo','property','green'],['Hong Kong','property','darkBlue'],['Orient Express','railroad',undefined],['Trans-Siberian Rail','railroad',undefined],['Power Grid','utility',undefined],['Waterworks','utility',undefined]];
export const cards:C.PropertyCardProps[]=rows.map(([name,type,colorGroup],i)=>({property:{id:`p${i}`,name,type,colorGroup,baseValue:2000000,currentValue:2200000,rent:type==='railroad'?[25000,50000,100000,200000]:type==='utility'?[0]:i<2?[2000,10000,30000,90000,160000,250000]:[10000,50000,150000,450000,625000,750000],mortgageValue:1000000,houseCost:50000,hotelCost:250000,houses:i===0?2:0,hasHotel:i===2,owner:i===7?undefined:i===5?'Priya':'You',isOwned:i!==7,isMortgaged:i===1,isInAuction:i===4,isInactive:i===6,position:i+1},rentNow:type==='utility'?'Dice × $4K (both: × $10K)':i===0?30000:i===2?750000:10000,mortgageAmount:1100000,owner:{name:i===5?'Priya':'You',color:'#06b6d4',icon:'🌊',isYou:i!==5,teamName:i===0?'Cyan Alliance':undefined},hasMonopoly:i<2,teamBoosted:i===0,hidden:i===11,actions:[{id:'build-house',label:'Build house · $150K',onAction:()=>{},disabledReason:i===1?'Unmortgage before building.':undefined},{id:'build-hotel',label:'Build hotel · $250K',onAction:()=>{},disabledReason:'Build four even houses first.'},{id:'sell',label:'Sell building · +$50K',onAction:()=>{}},{id:'mortgage',label:'Mortgage · +$1.1M',onAction:()=>{},disabledReason:'Sell buildings across the group first.'},{id:'unmortgage',label:'Unmortgage · −$1.2M',onAction:()=>{}}]}));
export function CardsPreview({scene='portfolio'}:{scene?:string}){
 const [ordered,setOrdered]=useState(cards);const [message,setMessage]=useState('Ready');const [selection,setSelection]=useState(['p0']);const [inspect,setInspect]=useState(scene.startsWith('inspect'));const [reveal,setReveal]=useState(scene!=='chance-back');const [banner,setBanner]=useState(true);
 const observed=ordered.map(c=>({...c,actions:c.actions?.map(a=>({...a,onAction:()=>setMessage(a.id)}))}));
 let content:React.ReactNode;
 if(scene==='portfolio')content=<><C.CardRail cards={observed} onReorder={ids=>setOrdered(ids.map(id=>ordered.find(c=>c.property.id===id)!))}/><C.JailCard count={2} onUse={()=>setMessage('Jail card requested')}/></>;
 else if(scene==='grid')content=<C.CardGrid cards={observed}/>;
 else if(scene==='performance')content=<C.CardGrid cards={Array.from({length:40},(_,i)=>({...observed[i%12],property:{...observed[i%12].property,id:`perf${i}`,name:observed[i%12].property.name},hidden:false}))}/>;
 else if(scene.startsWith('inspect'))content=<><KitButton onClick={()=>setInspect(true)}>Inspect {scene==='inspect-london'?'London':scene==='inspect-singapore'?'Singapore':'Tokyo'}</KitButton>{inspect&&<C.InspectView {...observed[scene==='inspect-london'?0:scene==='inspect-singapore'?5:2]} onClose={()=>setInspect(false)} onMoveRight={()=>setMessage('Moved right')}/>}</>;
 else if(scene==='trade')content=<C.TradeCardPicker label="You give" choices={observed.slice(0,5).map((card,i)=>({card,lockedReason:i===1?'Buildings in this colour group prevent trading.':undefined}))} selectedIds={selection} onToggle={id=>setSelection(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}/>;
 else if(scene==='auction')content=<C.AuctionCard card={observed[4]} auction={{propertyName:'Dubai',currentBid:1250000,highestBidder:'Priya',you:'You',secondsLeft:8,totalSeconds:120,minIncrement:10000,quickBids:[1260000,1300000,20000000],balance:10234567,isSeller:false,hasBid:true,isDraft:true,onBid:amount=>setMessage(`Bid ${amount}`)}}/>;
 else if(scene==='doubles')content=<><C.DoublesBanner visible={banner} onFinished={()=>setBanner(false)}/><C.DoublesBanner triple/><C.JailCard count={1}/></>;
 else if(scene==='special')content=<div className="cards-special">{(['go-to-jail','free-parking','pass-go'] as const).map(kind=><C.RevealCard key={kind} kind={kind} title={kind==='go-to-jail'?'Straight to jail':kind==='free-parking'?'The pot is yours':'Passed GO'} amount={kind==='go-to-jail'?undefined:250000} lines={[kind==='go-to-jail'?'Your next turn begins in jail.':'Amount supplied by the game adapter.']} revealed onContinue={()=>setMessage(kind)} continueLabel="Continue"/>)}</div>;
 else content=<C.RevealCard kind={scene==='community'?'community':'chance'} title={scene==='community'?'A double with a silver lining':'An unexpected expense'} amount={scene==='community'?-120000:-80000} lines={[scene==='community'?'Roll 6 · even → penalty':'Roll 8 · even → penalty',scene==='community'?'Rental income $1.2M × 10% = $120K':'Rental income $800K × 10% = $80K','Rule and amount are supplied by the game adapter.']} perk={scene==='community'?'GET OUT OF JAIL FREE card earned (double roll)':undefined} revealed={scene==='chance-back'?undefined:reveal} onReveal={()=>setMessage('Revealed once')} onContinue={()=>setMessage('Continue requested')} continueLabel="Pay"/>;
 return <main className="mma-ui cards-fixture"><h1>Global Edition · {scene}</h1><p role="status">{message}</p>{content}<div className="cards-scroll-proof"><p>Background remains scrollable while inspecting a property.</p><p>End of fixture board.</p></div></main>;
}
